// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0uC55ZB4m19paGaO9IlzJDABo629hobc',
    appId: '1:289066538277:web:1b9de8d539d355ed1a76cc',
    messagingSenderId: '289066538277',
    projectId: 'millenium-ccd4a',
    authDomain: 'millenium-ccd4a.firebaseapp.com',
    storageBucket: 'millenium-ccd4a.appspot.com',
    measurementId: 'G-V0DXFWMLE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYuH9V0Cg6lxQKyjNG628BLVXBaQ4FwWY',
    appId: '1:289066538277:android:7afaf1b0c21d6a1e1a76cc',
    messagingSenderId: '289066538277',
    projectId: 'millenium-ccd4a',
    storageBucket: 'millenium-ccd4a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0uC55ZB4m19paGaO9IlzJDABo629hobc',
    appId: '1:289066538277:web:4fa4c360cdc94c2e1a76cc',
    messagingSenderId: '289066538277',
    projectId: 'millenium-ccd4a',
    authDomain: 'millenium-ccd4a.firebaseapp.com',
    storageBucket: 'millenium-ccd4a.appspot.com',
    measurementId: 'G-HNB273HC9M',
  );
}
